package com.empresa.sankya.licenca;

public enum TipoDeLicenca {
    LICENCA_DE_FUNCIONAMENTO,
    ALVARA_PARA_TRANSPORTE_E_DEPOSITO,
    CERTIFICADO_DE_REGISTRO_PARA_TRANSPORTE,
    AUTORIZACAO_DE_FUNCIONAMENTO_E_ALVARA_SANITARIO;
}
